services:
  frontend:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8080/api
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=eusouobatman
    # volumes:
    #   - ./ui:/app:cached
    depends_on:
      - backend
    networks:
      - api_network

  backend:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:docker@findev-db:5432/findev-db?schema=public"
    ports:
      - "8080:8080"
    volumes:
      - ./api:/home/app:cached
      - ./api/package.json:/home/app/package.json:cached
    depends_on:
      database:
        condition: service_healthy
    networks:
      - api_network

  database:
    image: postgres:14.4-alpine
    container_name: findev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: findev-db
    ports:
      - 5432:5432
    networks:
      - api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  api_network:
