FROM node:22.13.1-alpine as builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

FROM node:22.13.1-alpine

WORKDIR /app

RUN apk add --no-cache bash

COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.docker ./.docker

RUN chmod +x .docker/entrypoint.sh

EXPOSE 8080

ENTRYPOINT [".docker/entrypoint.sh"]
